CREATE DATABASE baza;
USE baza;
CREATE TABLE uzytkownicy ( uID int NOT NULL PRIMARY KEY AUTO_INCREMENT, email varchar(255) NOT NULL, haslo varchar(255) NOT NULL);
CREATE TABLE magazyny( mID int NOT NULL PRIMARY KEY AUTO_INCREMENT, nazwa varchar(255) NOT NULL, adres varchar(255) NOT NULL, telefon varchar(255)  NOT NULL, ID_u int NOT NULL, FOREIGN KEY (ID_u) REFERENCES uzytkownicy(uID));
CREATE TABLE zleceniodawcy( zID int NOT NULL PRIMARY KEY AUTO_INCREMENT, nazwa varchar(255) not null, adres varchar(255) not null, telefon varchar(255) not null, ID_u int NOT NULL, FOREIGN KEY (ID_u) REFERENCES uzytkownicy(uID));
CREATE TABLE firmy_dostawcze( fdID int NOT NULL PRIMARY KEY AUTO_INCREMENT, nazwa varchar(255) not null, adres varchar(255) not null, telefon varchar(255) not null, ID_u int NOT NULL, FOREIGN KEY (ID_u) REFERENCES uzytkownicy(uID));
CREATE TABLE zlecenia_dostawy(nr_referencyjny int NOT NULL PRIMARY KEY, towar varchar(255) not null, ilosc varchar(255) not null, skadID INT NOT NULL, dokadID INT NOT NULL, oczekiwany_czas_dostawy DATETIME, wykonawcaID int, FOREIGN KEY (wykonawcaID) REFERENCES firmy_dostawcze(fdID), FOREIGN KEY (skadID) REFERENCES magazyny(mID), FOREIGN KEY (dokadID) REFERENCES magazyny(mID));
INSERT INTO uzytkownicy (email, haslo) VALUES ('wzium@gmail.com', 'haslo123');
INSERT INTO uzytkownicy VALUES (2, 'szybkadostawa@gmail.com', 'hasloikea23');
INSERT INTO uzytkownicy VALUES (3, 'marcin@gmail.com', 'das23');
INSERT INTO uzytkownicy VALUES (4, 'czarek@gmail.com', 'dagfdgds23');
INSERT INTO uzytkownicy VALUES (5, 'wojtek@gmail.com', 'dagfdgds23');
INSERT INTO uzytkownicy VALUES (6, 'jazdunia@gmail.com', 'dczxds23');
INSERT INTO uzytkownicy VALUES (7, 'wielkimagazyn@gmail.com', 'dczxds23');
INSERT INTO uzytkownicy VALUES (8, 'niebieskimagazyn@gmail.com', 'dczxds23');
INSERT INTO uzytkownicy VALUES (9, 'mojmagazyn@gmail.com', 'dczxds23');
INSERT INTO magazyny VALUES (1, 'Wielki magazyn', 'Poznanska, Wroclaw', '123456544', 7);
INSERT INTO magazyny VALUES (2, 'Niebieski magazyn', 'Opatowicka, Warszawa', '+4832156544', 8);
INSERT INTO magazyny VALUES (3, 'Jego magazyn', 'Sokolska, Katowice', '+4832153424', 9);
INSERT INTO zleceniodawcy VALUES (1, 'Czarek', 'Katowicka, Chorzów', '+483321424', 4);
INSERT INTO zleceniodawcy VALUES (2, 'Wojtek', 'Piotrkowska, Łódź', '+48647424', 5);
INSERT INTO zleceniodawcy VALUES (3, 'Marcin', 'Wyszyńska, Łódź', '+4875657624', 3);
INSERT INTO firmy_dostawcze VALUES(1, 'Jazdunia', 'Bierutna, Zabrze', '+481234124', 6);
INSERT INTO firmy_dostawcze VALUES(2, 'Ikea Dostawy', 'Biała, Gdańsk', '+48789124', 2);
INSERT INTO firmy_dostawcze VALUES(3, 'XYZ Dostawy', 'Zielona, Gdynia', '+48667898724', 1);
INSERT INTO zlecenia_dostawy VALUES (3423, 'Skrzynki 20kg jabłka', '50', 1, 3,'2020.05.19 16:00:00', 2);
INSERT INTO zlecenia_dostawy VALUES (1223, 'Filety z dorsza- skrzynka 10kg', '20', 2, 3,'2020.05.20 12:00:00', NULL);
INSERT INTO zlecenia_dostawy VALUES (7526, 'Majonez Kielecki- skrzynka 20kg', '100', 2, 1,'2020.06.05 13:30:00', 1);